name: hackathon
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

resolution: workspace


flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  assets:
    path: ../packages/assets

  flutter_svg: ^2.1.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  talker_flutter: ^4.7.2
  talker_riverpod_logger: ^4.7.1
  talker_dio_logger: ^4.7.1
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  jwt_decoder: ^2.0.1
  flutter_appauth: ^9.0.0
  auto_route: ^10.0.1
  shared_preferences: ^2.5.3
  gap: ^3.0.1
  theme_tailor: ^3.0.2
  theme_tailor_annotation: ^3.0.2
  blur: ^4.0.2
  smooth_page_indicator: ^1.2.1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  animations: ^2.0.11
  timeago: ^3.7.1
  equatable: ^2.0.7
  synchronized: ^3.3.1
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  device_preview_plus: ^2.4.1
  collection: ^1.19.1
  cached_network_image: ^3.4.1
  file_picker: ^8.0.0+1
  share_plus: ^11.0.0
  path_provider: ^2.1.4
  args: ^2.4.2
  flutter_libserialport:
    git: https://github.com/jpnurmi/flutter_libserialport
  image: ^4.0.17
  infinite_scroll_pagination:
  meta:
  intl: ^0.20.2
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  slang_build_runner: ^4.7.0
  flutter_gen_runner:
  flutter_lints: ^6.0.0
