name: assets
description: >
  Holds the assets for the app. The assets are included in a
  separate package, to be able to share it with Widgetbook app.

version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace


dependencies:
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.11

flutter:
  assets:
    - vector/
    - raster/

  fonts:
    - family: LamaSans
      fonts:
        - asset: font/LamaSans-SemiBold.ttf
          weight: 600
        - asset: font/LamaSans-Bold.ttf
          weight: 700

flutter_gen:
  # Optional
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true # <- Add this line.
